---
title: My First Blog Post!
author: Rob Bailey
date: '2019-12-07'
slug: my-first-blog-post
categories: []
tags:
  - blog post
description: ''
---
```{r setup,include=FALSE}
library(reticulate)
use_python("/opt/anaconda3/bin/python3")
#use_virtualenv("r-reticulate")
Sys.setenv(RETICULATE_PYTHON="/opt/anaconda3/bin/python3")
```



```{python}
2+2
```

## Excited to be here!

I'm Rob, and as an environmental scientist and aspiring marine biologist, coding and understanding how to work with large datasets is important to me and for my future career. Through the course of my undergraduate career at the University of Texas, I've had a wonderful amount of exposure to various statistics classes, coding classes, among others, and these classes have given me the groundwork for being knowledgeable in modeling, bioinformatics, and data wrangling. 

In the short time of the course of a semester, we've worked mostly with RStudio in SDS 348 (Computational Bio and Bioinformatics), but towards the end, we've moved to Python. With Python, we've been introduced to the basics, regular expressions, for-loops, some algorithms (e.g. Needleman-Wunsch Algorithm), among other things.
```{python}
import pandas
import numpy as np
import seaborn as sns
```

```{python}
tips = sns.load_dataset('tips')
tips.describe()
```

```{python}
iris = sns.load_dataset('iris')
iris.describe()
```

```{python}
#using pandas groupby functionality
groups = tips.groupby('sex')
groups['tip'].mean()
```

```{python}
sns.pairplot(iris, hue='species');
```



